name: Linux
on: [push]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
        configure: [""]
        include:
          - compiler: gcc
            configure: "--disable-c-pkgconfig --disable-c-pages --disable-c-fsindex --disable-c-readerchannel --disable-c-writerchannel --disable-c-vfs"
          - compiler: gcc
            configure: "--disable-c-pages --disable-c-fsindex --disable-c-readerchannel --disable-c-writerchannel --disable-c-vfs"
          - compiler: gcc
            configure: "--disable-c-fsindex --disable-c-readerchannel --disable-c-writerchannel --disable-c-vfs"
          - compiler: gcc
            configure: "--disable-c-readerchannel --disable-c-writerchannel --disable-c-vfs"
          - compiler: gcc
            configure: "--disable-c-writerchannel --disable-c-vfs"
          - compiler: gcc
            configure: "--disable-c-vfs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Environment (compiler=${{ matrix.compiler }})
        run: |
          sudo apt-get install tcl8.6-dev tcl-vfs
          mkdir "$HOME/install dir"
          echo "CFGOPT_COMMON=--with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
          echo "CFGOPT_CUSTOM=\"$CONFIGURE\"" >> $GITHUB_ENV
          echo "CC=$COMPILER" >> $GITHUB_ENV
        env:
          COMPILER: ${{ matrix.compiler }}
          OPTS: ${{ matrix.compiler }}
          CONFIGURE: ${{ matrix.configure }}
      - name: Configure
        run: |
          set -x
          ./configure $CFGOPT_COMMON $CFGOPT_CUSTOM "--prefix=$HOME/install dir" "--exec-prefix=$HOME/install dir" || {
            cat config.log
            echo "::error::Failure during Configure"
            exit 1
          }
      - name: Build
        run: |
          make || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        run: |
          make test || {
            echo "::error::Failure during Test"
            exit 1
          }
        env:
          ERROR_ON_FAILURES: 1
      - name: Test-Drive Installation
        run: |
          make install || {
            echo "::error::Failure during Install"
            exit 1
          }
      - name: Create Distribution Package
        run: |
          make dist || {
            echo "::error::Failure during Distribute"
            exit 1
          }
