name: Linux (without Tcl commands)
on: [push]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
    name: build (${{ matrix.compiler }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Environment (compiler=${{ matrix.compiler }})
        run: |
          sudo apt-get install tcl8.6-dev tcl-thread
          mkdir "$HOME/install dir"
          echo "CFGOPT_COMMON=--with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
          echo "CC=$COMPILER" >> $GITHUB_ENV
        env:
          COMPILER: ${{ matrix.compiler }}
          OPTS: ${{ matrix.compiler }}
      - name: Configure
        run: |
          ./configure $CFGOPT_COMMON --disable-tcl-commands "--prefix=$HOME/install dir" "--exec-prefix=$HOME/install dir" || {
            cat config.log
            echo "::error::Failure during Configure"
            exit 1
          }
      - name: Build
        run: |
          make -j || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        run: |
          make test || {
            echo "::error::Failure during Test"
            exit 1
          }
      - name: Test-Drive Installation
        run: |
          make install || {
            echo "::error::Failure during Install"
            exit 1
          }
      - name: Create Distribution Package
        run: |
          make dist || {
            echo "::error::Failure during Distribute"
            exit 1
          }
